### For helm chart deployment you can refere https://github.com/devopshint/Deploy-java-helm-chart-on-EKS-using-GitHub-Actions/blob/main/.github/workflows/main.yml
name: Test inputs using conditions
on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: string
      deploy_target:
        required: true
        type: string
      perform_deploy:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy == 'dev' }}
    steps:
      - name: Deploy build to target
        run: echo "deploy --build ${{ inputs.build_id }} --target ${{ inputs.deploy_target }}"
